name: deliverzler
description: Deliverzler
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

  #StateManagement
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3

  #Responsive
  flutter_screenutil: ^5.3.1

  #Connectivity
  connectivity_plus: ^2.1.0
  internet_connection_checker: ^0.0.1+3

  #Location
  location: ^4.3.0
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0

  #Apis
  dio: ^4.0.4

  #Firebase
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  firebase_messaging: ^11.2.5

  #LocalStorage
  shared_preferences: ^2.0.9
  sqflite: ^2.0.1
  image_picker: ^0.8.4+4

  #Images
  cached_network_image: ^3.2.0
  lottie: ^1.2.1

  #Utils
  freezed_annotation: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_fadein: ^2.0.0
  uuid: ^3.0.5
  url_launcher: ^6.0.18
  flutter_local_notifications: ^9.2.0

  #Widgets
  qr_flutter: ^4.0.0
  material_floating_search_bar: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  build_runner: ^2.1.7
  freezed: ^1.1.1

flutter_icons:
  image_path_android: "assets/images/core/icon.png"
  image_path_ios: "assets/images/core/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"

flutter_native_splash:
  background_image: "assets/images/welcome/splash_light.png"
  background_image_dark: "assets/images/welcome/splash_dark.png"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/json/
    - assets/json/map_styles/
    - assets/images/welcome/
    - assets/images/login/
    - assets/images/core/
    - assets/images/core/dialog_widget_icons/
    - assets/images/app_icons/
    - assets/images/app_icons/screens_icons/
    - assets/images/app_icons/languages_icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 900
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf
        - asset: assets/fonts/tajawal_bold.ttf
          weight: 900